version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - /data/db
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: flash-cards
    links:
      - mongo
volumes:
  db: