version: '3'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    volumes:
      - /data/db
  java:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: flash-cards-be
    links:
      - mongo
  flutter:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: flash-cards-fe
volumes:
  db: